import type { NextPage } from 'next'
import Head from 'next/head'
import BaseLayout from '../components/core/BaseLayout'
import PaperPanel from '../components/PaperPanel'

const Home: NextPage = () => {
  return (
    <BaseLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <PaperPanel>
        <p>hello paper</p>
        <p>hello</p>
      </PaperPanel>
      </main>
    </BaseLayout>
    )
}

export default Home
